type InsuranceClaim = {
  id: number;
  title: string;
  value: number;
};

export function exportInsuranceWhatsapp(
  claims: InsuranceClaim[]
) {
  const totalClaims = claims.reduce(
    (sum, item) => sum + item.value,
    0
  );

  const generatedOn = new Date().toLocaleString("en-IN");

  const report = `
🏥 *LEADS HEALTH CARE*

══════════════════════
📋 *INSURANCE CLAIM STATUS REPORT*
══════════════════════

🗓 Generated On
${generatedOn}

📊 Total Claims : *${totalClaims}*

──────────────────────

${claims
  .map((claim) => {
    const percentage = (
      (claim.value / totalClaims) *
      100
    ).toFixed(1);

    let icon = "📄";

    switch (claim.title) {
      case "Claims Submitted":
        icon = "📤";
        break;

      case "Claims Approved":
        icon = "✅";
        break;

      case "Claims Pending":
        icon = "🕒";
        break;

      case "Claims Rejected":
        icon = "❌";
        break;
    }

    return `${icon} *${claim.title}*
   • Claims      : ${claim.value}
   • Percentage : ${percentage}%`;
  })
  .join("\n\n")}

──────────────────────

📈 *Summary*

${claims
  .map((c) => `• ${c.title}: ${c.value}`)
  .join("\n")}

──────────────────────

Generated by
*Leads Health Care Dashboard*
`;

  const url =
    "https://wa.me/?text=" +
    encodeURIComponent(report);

  window.open(url, "_blank");
}