import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type Claim = {
  id: number;
  title: string;
  value: number;
};

export const exportInsurancePDF = (
  claims: Claim[]
) => {
  const doc = new jsPDF("p", "mm", "a4");

  const submitted =
    claims.find(c => c.title === "Claims Submitted")?.value ?? 0;

  const approved =
    claims.find(c => c.title === "Claims Approved")?.value ?? 0;

  const pending =
    claims.find(c => c.title === "Claims Pending")?.value ?? 0;

  const rejected =
    claims.find(c => c.title === "Claims Rejected")?.value ?? 0;

  const approvalRate =
    submitted === 0
      ? 0
      : ((approved / submitted) * 100);

  //------------------------------------------------

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("LEADS HEALTH CARE", 105, 18, {
    align: "center",
  });

  doc.setFontSize(16);
  doc.text(
    "Insurance Claim Status Report",
    105,
    28,
    { align: "center" }
  );

  //------------------------------------------------

  doc.setDrawColor(180);
  doc.line(15, 34, 195, 34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  doc.text(
    `Generated On : ${new Date().toLocaleString()}`,
    15,
    42
  );

  doc.text(
    "Generated By : Dashboard Analytics",
    15,
    48
  );

  doc.text(
    "Report Type : Insurance Claims",
    15,
    54
  );

  //------------------------------------------------

  //------------------------------------------------
// Dynamic Summary Box
//------------------------------------------------

const summaryItems = [
  `Claims Submitted : ${submitted}`,
  `Approved : ${approved}`,
  `Pending : ${pending}`,
  `Rejected : ${rejected}`,
  `Approval Rate : ${approvalRate.toFixed(2)}%`,
];

const summaryTop = 62;
const titleHeight = 10;
const rowHeight = 8;

const rowCount = Math.ceil(summaryItems.length / 2);

const summaryHeight =
  titleHeight +
  rowCount * rowHeight +
  6;

doc.setFillColor(240, 245, 255);

doc.roundedRect(
  15,
  summaryTop,
  180,
  summaryHeight,
  2,
  2,
  "F"
);

doc.setFont("helvetica", "bold");
doc.setFontSize(13);

doc.text(
  "Summary",
  20,
  summaryTop + 10
);

doc.setFont("helvetica", "normal");
doc.setFontSize(11);

const leftX = 20;
const rightX = 110;

let y = summaryTop + 20;

doc.text(summaryItems[0], leftX, y);
doc.text(summaryItems[1], rightX, y);

y += rowHeight;

doc.text(summaryItems[2], leftX, y);
doc.text(summaryItems[3], rightX, y);

y += rowHeight;

doc.text(summaryItems[4], leftX, y);

//------------------------------------------------
  //------------------------------------------------

  autoTable(doc, {
    startY: summaryTop + summaryHeight + 10,

    head: [[
      "Status",
      "Claims",
      "Percentage",
      "Last Updated",
    ]],

    body: claims.map(claim => [

      claim.title,

      claim.value,

      `${(
        (claim.value / submitted) *
        100
      ).toFixed(2)}%`,

      new Date().toLocaleTimeString(),

    ]),

    theme: "grid",

    headStyles: {

      fillColor: [30, 64, 175],

      textColor: 255,

      fontStyle: "bold",

      halign: "center",

    },

    bodyStyles: {

      halign: "center",

      valign: "middle",

    },

    alternateRowStyles: {

      fillColor: [248, 250, 252],

    },

    styles: {

      fontSize: 10,

      cellPadding: 4,

    },

  });

  //------------------------------------------------

  const pageHeight = doc.internal.pageSize.height;

  doc.setDrawColor(220);

  doc.line(
    15,
    pageHeight - 20,
    195,
    pageHeight - 20
  );

  doc.setFontSize(10);

  doc.text(
    "Generated by Leads Health Care",
    105,
    pageHeight - 13,
    { align: "center" }
  );

  doc.text(
    "Confidential Hospital Report",
    105,
    pageHeight - 7,
    { align: "center" }
  );

  //------------------------------------------------

  doc.save("Insurance-Claim-Status-Report.pdf");
};