type Doctor = {
  id: number;
  name: string;
  department: string;
  patients: number;
  revenue: number;
  rating: number;
};

const money = (value: number) =>
  new Intl.NumberFormat("en-IN").format(value);

export function exportDoctorsWhatsapp(rows: Doctor[]) {
  if (!rows.length) {
    alert("No doctor records available.");
    return;
  }

  //------------------------------------
  // Summary
  //------------------------------------

  const totalRevenue = rows.reduce(
    (sum, row) => sum + row.revenue,
    0
  );

  const totalPatients = rows.reduce(
    (sum, row) => sum + row.patients,
    0
  );

  const avgRating =
    rows.reduce((sum, row) => sum + row.rating, 0) /
    rows.length;

  //------------------------------------
  // Report
  //------------------------------------

  let message = "";

  message += "🏥 *LEADS HEALTH CARE*\n";
  message += "━━━━━━━━━━━━━━━━━━━━━━\n";
  message += "*TOP PERFORMING DOCTORS REPORT*\n\n";

  message += `📅 Generated : ${new Date().toLocaleString()}\n\n`;

  //------------------------------------
  // Executive Summary
  //------------------------------------

  message += "📊 *EXECUTIVE SUMMARY*\n";
  message += "━━━━━━━━━━━━━━━━━━━━━━\n";

  message += `👨‍⚕️ Doctors : ${rows.length}\n`;
  message += `🩺 Patients : ${money(totalPatients)}\n`;
  message += `💰 Revenue : ₹${money(totalRevenue)}\n`;
  message += `⭐ Avg Rating : ${avgRating.toFixed(2)} / 5\n\n`;

  //------------------------------------
  // Doctor Details
  //------------------------------------

  message += "👨‍⚕️ *DOCTOR DETAILS*\n";
  message += "━━━━━━━━━━━━━━━━━━━━━━\n\n";

  rows.forEach((doctor, index) => {
    message += `${index + 1}. *${doctor.name}*\n`;
    message += `   🏥 Department : ${doctor.department}\n`;
    message += `   👥 Patients : ${money(doctor.patients)}\n`;
    message += `   💰 Revenue : ₹${money(doctor.revenue)}\n`;
    message += `   ⭐ Rating : ${doctor.rating}/5\n\n`;
  });

  //------------------------------------
  // Footer
  //------------------------------------

  message += "━━━━━━━━━━━━━━━━━━━━━━\n";
  message += "Generated by Leads Health Care Dashboard\n";
  message += "Confidential Report";

  //------------------------------------
  // Open WhatsApp
  //------------------------------------

  window.open(
    `https://wa.me/?text=${encodeURIComponent(message)}`,
    "_blank"
  );
}