import { formatCurrency } from "@/lib/formatCurrency";
import { formatPercent } from "@/lib/formatCurrency";

type RevenueExceptionRow = {
  department: string;
  expected: number;
  actual: number;
  variance: number;
  variancePercent: number;
  status: "Positive" | "Negative";
};

export function exportWhatsapp(
  rows: RevenueExceptionRow[]
) {
  const totalExpected = rows.reduce(
    (sum, row) => sum + row.expected,
    0
  );

  const totalActual = rows.reduce(
    (sum, row) => sum + row.actual,
    0
  );

  const totalVariance = totalActual - totalExpected;

  const positive = rows.filter(
    (r) => r.status === "Positive"
  ).length;

  const negative = rows.filter(
    (r) => r.status === "Negative"
  ).length;

  let report = "";

  report +=
`🏥 *LEADS HEALTH CARE*
━━━━━━━━━━━━━━━━━━━━━━━
📊 *REVENUE EXCEPTIONS REPORT*
━━━━━━━━━━━━━━━━━━━━━━━

📅 *Generated*
${new Date().toLocaleString()}

═══════════════════════
📈 *EXECUTIVE SUMMARY*
═══════════════════════

🏢 Departments : ${rows.length}

💰 Expected Revenue
₹${formatCurrency(totalExpected)}

💵 Actual Revenue
₹${formatCurrency(totalActual)}

📉 Total Variance
${totalVariance >= 0 ? "+" : "-"}₹${formatCurrency(
Math.abs(totalVariance)
)}

🟢 Positive : ${positive}

🔴 Negative : ${negative}

═══════════════════════
📋 *DETAILS*
═══════════════════════

`;

  rows.forEach((row, index) => {
    report +=
`${index + 1}. *${row.department}*

Expected : ₹${formatCurrency(row.expected)}

Actual : ₹${formatCurrency(row.actual)}

Variance :
${row.variance >= 0 ? "+" : "-"}₹${formatCurrency(
Math.abs(row.variance)
)}

Variance % :
${row.variance >= 0 ? "+" : "-"}${formatPercent(
Math.abs(row.variancePercent)
)}%

Status :
${row.status === "Positive"
? "🟢 Positive"
: "🔴 Negative"}

───────────────────────

`;
  });

  report +=
`Generated by
🏥 Leads Health Care`;

  window.open(
    `https://wa.me/?text=${encodeURIComponent(report)}`,
    "_blank"
  );
}