type VarianceItem = {
  id: number;
  metric: string;
  expected: number;
  actual: number;
  variance: number;
  variancePercentage: number;
  status: string;
};

export function ExportVariancePrint(
  data: VarianceItem[],
  status: string,
  metric: string,
  search: string
) {
  const formatNumber = (value: number) =>
    new Intl.NumberFormat("en-IN").format(value);

  const totalExpected = data.reduce((a, b) => a + b.expected, 0);
  const totalActual = data.reduce((a, b) => a + b.actual, 0);
  const totalVariance = data.reduce((a, b) => a + b.variance, 0);

  const positive = data.filter(
    (x) => x.status === "Positive"
  ).length;

  const negative = data.filter(
    (x) => x.status === "Negative"
  ).length;


  const html = `
<!DOCTYPE html>
<html>

<head>

<title>Variance Analysis Report</title>

<style>

*{
box-sizing:border-box;
font-family:Arial,Helvetica,sans-serif;
}

body{
margin:30px;
color:#1f2937;
background:#fff;
}

.header{
display:flex;
justify-content:space-between;
align-items:flex-start;
border-bottom:3px solid #1e40af;
padding-bottom:14px;
margin-bottom:25px;
}

.title{
font-size:28px;
font-weight:700;
color:#1e40af;
}

.subtitle{
font-size:14px;
color:#666;
margin-top:4px;
}

.info{
text-align:right;
font-size:13px;
line-height:1.8;
}

.filters{
display:flex;
justify-content:space-between;
background:#f8fafc;
border:1px solid #dbeafe;
padding:12px 18px;
border-radius:8px;
margin-bottom:22px;
font-size:14px;
}

.cards{
display:grid;
grid-template-columns:repeat(5,1fr);
gap:16px;
margin-bottom:25px;
}

.card{
border-radius:10px;
padding:18px;
text-align:center;
color:#fff;
}

.card h4{
margin:0;
font-size:14px;
font-weight:500;
}

.card h2{
margin:12px 0 0;
font-size:28px;
}

.blue{background:#2563eb;}
.green{background:#16a34a;}
.red{background:#dc2626;}
.orange{background:#ea580c;}
.gray{background:#475569;}

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
}

thead{
background:#1e40af;
color:#fff;
}

th{
padding:12px;
border:1px solid #cbd5e1;
text-align:center;
}

td{
padding:11px;
border:1px solid #e2e8f0;
text-align:center;
}

tbody tr:nth-child(even){
background:#f8fafc;
}

.badge{
display:inline-block;
padding:5px 14px;
border-radius:999px;
font-size:12px;
font-weight:600;
}

.positive{
background:#dcfce7;
color:#166534;
}

.negative{
background:#fee2e2;
color:#991b1b;
}

.neutral{
background:#e2e8f0;
color:#334155;
}

.footer{
margin-top:30px;
display:flex;
justify-content:space-between;
font-size:12px;
color:#666;
border-top:1px solid #ddd;
padding-top:10px;
}

@media print{

body{
margin:10mm;
}

button{
display:none;
}

}

</style>

</head>

<body>

<div class="header">

<div>

<div class="title">
Variance Analysis Report
</div>

<div class="subtitle">
Leads Health Care
</div>

</div>

<div class="info">

<div>
Generated :
${new Date().toLocaleString("en-IN")}
</div>

<div>
Total Metrics :
${data.length}
</div>

</div>

</div>

<div class="filters">

<div>
<b>Status:</b>
${status === "all" ? "All" : status}
</div>

<div>
<b>Metric:</b>
${metric === "all" ? "All" : metric}
</div>

<div>
<b>Search:</b>
${search || "-"}
</div>

</div>

<div class="cards">

<div class="card blue">
<h4>Total Expected</h4>
<h2>${formatNumber(totalExpected)}</h2>
</div>

<div class="card green">
<h4>Total Actual</h4>
<h2>${formatNumber(totalActual)}</h2>
</div>

<div class="card orange">
<h4>Total Variance</h4>
<h2>${formatNumber(totalVariance)}</h2>
</div>

<div class="card gray">
<h4>Positive</h4>
<h2>${positive}</h2>
</div>

<div class="card red">
<h4>Negative</h4>
<h2>${negative}</h2>
</div>

</div>

<table>

<thead>

<tr>

<th>Metric</th>
<th>Expected</th>
<th>Actual</th>
<th>Variance</th>
<th>Variance %</th>
<th>Status</th>

</tr>

</thead>

<tbody>

${data
  .map(
    (item) => `
<tr>

<td>${item.metric}</td>

<td>${formatNumber(item.expected)}</td>

<td>${formatNumber(item.actual)}</td>

<td>${formatNumber(item.variance)}</td>

<td>${item.variancePercentage.toFixed(2)}%</td>

<td>

<span class="badge ${
      item.status === "Positive"
        ? "positive"
        : item.status === "Negative"
        ? "negative"
        : "neutral"
    }">

${item.status}

</span>

</td>

</tr>
`
  )
  .join("")}

</tbody>

</table>

<div class="footer">

<div>
Leads Health Care • Variance Analysis Report
</div>

<div>
Generated by MIS Dashboard
</div>

</div>

<script>

window.onload=function(){

window.print();

setTimeout(()=>window.close(),300);

}

</script>

</body>

</html>
`;

  const printWindow = window.open("", "_blank");

  if (!printWindow) return;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}