import ExcelJS from "exceljs";
import { saveAs } from "file-saver";

type Variance = {
  id: number;
  metric: string;
  expected: number;
  actual: number;
  variance: number;
  variancePercentage: number;
  status: string;
};

export async function ExportVarianceExcel(
  data: Variance[],
  status: string,
  metric: string,
  search: string
) {
  const workbook = new ExcelJS.Workbook();

  workbook.creator = "Leads Health Care";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet("Variance Analysis", {
    properties: {
      defaultRowHeight: 22,
    },
    views: [
      {
        state: "frozen",
        ySplit: 6,
      },
    ],
  });

  // Widths
  sheet.columns = [
    { width: 8 },
    { width: 30 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
    { width: 18 },
  ];

  // Hospital Name
  sheet.mergeCells("A1:G1");
  sheet.getCell("A1").value = "LEADS HEALTH CARE";

  sheet.getCell("A1").font = {
    size: 18,
    bold: true,
    color: { argb: "1E3A8A" },
  };

  sheet.getCell("A1").alignment = {
    horizontal: "center",
  };

  // Report Title
  sheet.mergeCells("A2:G2");
  sheet.getCell("A2").value = "Variance Analysis Report";

  sheet.getCell("A2").font = {
    size: 14,
    bold: true,
  };

  sheet.getCell("A2").alignment = {
    horizontal: "center",
  };

  // Filters
  sheet.mergeCells("A3:G3");

  sheet.getCell("A3").value =
    `Generated : ${new Date().toLocaleString("en-IN")}
     | Status : ${status}
     | Metric : ${metric}
     | Search : ${search || "-"}`;

  sheet.getCell("A3").font = {
    italic: true,
    size: 10,
  };

  // Summary
  sheet.mergeCells("A4:G4");
  sheet.getCell("A4").value = `Total Records : ${data.length}`;

  sheet.getCell("A4").font = {
    bold: true,
  };

  // Header
  const header = sheet.addRow([
    "#",
    "Metric",
    "Expected",
    "Actual",
    "Variance",
    "Variance %",
    "Status",
  ]);

  header.height = 24;

  header.eachCell((cell) => {
    cell.font = {
      bold: true,
      color: { argb: "FFFFFF" },
    };

    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: {
        argb: "2563EB",
      },
    };

    cell.alignment = {
      horizontal: "center",
      vertical: "middle",
    };

    cell.border = {
      top: { style: "thin" },
      bottom: { style: "thin" },
      left: { style: "thin" },
      right: { style: "thin" },
    };
  });

  // Rows
  data.forEach((item, index) => {
    const row = sheet.addRow([
      index + 1,
      item.metric,
      item.expected,
      item.actual,
      item.variance,
      `${item.variancePercentage.toFixed(2)}%`,
      item.status,
    ]);

    row.eachCell((cell) => {
      cell.border = {
        top: { style: "thin" },
        bottom: { style: "thin" },
        left: { style: "thin" },
        right: { style: "thin" },
      };

      cell.alignment = {
        horizontal: "center",
        vertical: "middle",
      };
    });

    // Alternate row colors
    if (index % 2 === 0) {
      row.eachCell((cell) => {
        cell.fill = {
          type: "pattern",
          pattern: "solid",
          fgColor: {
            argb: "F8FAFC",
          },
        };
      });
    }

    // Status Color
    const statusCell = row.getCell(7);

    if (item.status === "Positive") {
      statusCell.font = {
        bold: true,
        color: { argb: "15803D" },
      };
    } else {
      statusCell.font = {
        bold: true,
        color: { argb: "DC2626" },
      };
    }

    // Variance color
    const varianceCell = row.getCell(5);

    varianceCell.font = {
      bold: true,
      color: {
        argb:
          item.variance >= 0
            ? "15803D"
            : "DC2626",
      },
    };

    // Variance % color
    const percentCell = row.getCell(6);

    percentCell.font = {
      bold: true,
      color: {
        argb:
          item.variancePercentage >= 0
            ? "15803D"
            : "DC2626",
      },
    };
  });

  // Footer
  const footerRow = sheet.addRow([]);

  footerRow.height = 12;

  sheet.mergeCells(`A${footerRow.number + 1}:G${footerRow.number + 1}`);

  sheet.getCell(`A${footerRow.number + 1}`).value =
    "Generated by Leads Health Care MIS Dashboard";

  sheet.getCell(`A${footerRow.number + 1}`).font = {
    italic: true,
    size: 10,
    color: { argb: "6B7280" },
  };

  sheet.getCell(`A${footerRow.number + 1}`).alignment = {
    horizontal: "center",
  };

  const buffer = await workbook.xlsx.writeBuffer();

  saveAs(
    new Blob([buffer]),
    `Variance_Analysis_${new Date()
      .toISOString()
      .slice(0, 10)}.xlsx`
  );
}